version: '3'
services:
  web:
    container_name: textler-client
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"